"""Constantes compartidas del modulo de comunicacion BoviSense-AI."""

from __future__ import annotations

ALLOWED_COMMANDS: tuple[str, ...] = (
    "PING",
    "GET_STATUS",
    "GET_DEVICE_INFO",
    "START_TASK",
    "STOP_TASK",
)

ACK = "ACK"
NACK = "NACK"

DEFAULT_SOURCE_APP = "mobile_app"
DEFAULT_ESP32_NODE = "esp32_bridge"
DEFAULT_JETSON_NODE = "jetson_orin_nano"

PROTOCOL_VERSION = "1.0.0"

ERROR_INVALID_JSON = "INVALID_JSON"
ERROR_INVALID_SCHEMA = "INVALID_SCHEMA"
ERROR_INVALID_CHECKSUM = "INVALID_CHECKSUM"
ERROR_COMMAND_NOT_ALLOWED = "COMMAND_NOT_ALLOWED"
ERROR_SEQUENCE_INVALID = "SEQUENCE_INVALID"
ERROR_PROCESSING_FAILED = "PROCESSING_FAILED"

