// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsMBREuN3BDoLAOhp6R61cxdAgybbKf8',
    appId: '1:357827375010:web:5135090c5c89784b5dccfb',
    messagingSenderId: '357827375010',
    projectId: 'aplicacion-cabfa',
    authDomain: 'aplicacion-cabfa.firebaseapp.com',
    storageBucket: 'aplicacion-cabfa.firebasestorage.app',
    measurementId: 'G-1DHT9CRG2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPjrjCmA_44j0YjxFbAv_XoctzDwtiqw',
    appId: '1:357827375010:android:00f2f5f7a21fde755dccfb',
    messagingSenderId: '357827375010',
    projectId: 'aplicacion-cabfa',
    storageBucket: 'aplicacion-cabfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZ6VxzPol_yJGQibg8XT3pOQ1NJqAbkc',
    appId: '1:357827375010:ios:66eeb684db16c9485dccfb',
    messagingSenderId: '357827375010',
    projectId: 'aplicacion-cabfa',
    storageBucket: 'aplicacion-cabfa.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZ6VxzPol_yJGQibg8XT3pOQ1NJqAbkc',
    appId: '1:357827375010:ios:66eeb684db16c9485dccfb',
    messagingSenderId: '357827375010',
    projectId: 'aplicacion-cabfa',
    storageBucket: 'aplicacion-cabfa.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJsMBREuN3BDoLAOhp6R61cxdAgybbKf8',
    appId: '1:357827375010:web:fffd418f781cb9ec5dccfb',
    messagingSenderId: '357827375010',
    projectId: 'aplicacion-cabfa',
    authDomain: 'aplicacion-cabfa.firebaseapp.com',
    storageBucket: 'aplicacion-cabfa.firebasestorage.app',
    measurementId: 'G-15TY9DJ6X6',
  );
}
